/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gcm;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Client
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil1
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patient = new javax.swing.JLabel();
        facture = new javax.swing.JLabel();
        consultation = new javax.swing.JLabel();
        rdv = new javax.swing.JLabel();
        dec = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gcm/image/patient1.jpg"))); // NOI18N
        patient.setText("jLabel2");
        patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientMouseClicked(evt);
            }
        });
        getContentPane().add(patient);
        patient.setBounds(330, 160, 160, 170);

        facture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gcm/image/factur.jpg"))); // NOI18N
        facture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                factureMouseClicked(evt);
            }
        });
        getContentPane().add(facture);
        facture.setBounds(550, 350, 160, 170);

        consultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gcm/image/consultation1.png"))); // NOI18N
        consultation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultationMouseClicked(evt);
            }
        });
        getContentPane().add(consultation);
        consultation.setBounds(550, 160, 160, 170);

        rdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gcm/image/rdv1.jpg"))); // NOI18N
        rdv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdvMouseClicked(evt);
            }
        });
        getContentPane().add(rdv);
        rdv.setBounds(330, 350, 160, 170);

        dec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gcm/image/deconnexion.jpg"))); // NOI18N
        dec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decMouseClicked(evt);
            }
        });
        getContentPane().add(dec);
        dec.setBounds(680, 70, 80, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gcm/image/BIEN.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 160, 230, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gcm/image/acc1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_decMouseClicked

    private void patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseClicked
        try {
            // TODO add your handling code here:
            new ListePatient().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_patientMouseClicked

    private void consultationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultationMouseClicked
        try {
            // TODO add your handling code here:
            new ListeConsultation().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_consultationMouseClicked

    private void rdvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdvMouseClicked
        try {
            // TODO add your handling code here:
            new ListeRdv().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_rdvMouseClicked

    private void factureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_factureMouseClicked
        try {
            // TODO add your handling code here:
            new ListeFacture().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
         dispose();
    }//GEN-LAST:event_factureMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
                new Accueil().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultation;
    private javax.swing.JLabel dec;
    private javax.swing.JLabel facture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel patient;
    private javax.swing.JLabel rdv;
    // End of variables declaration//GEN-END:variables
}
